- name: Change kali user shell to bash
  ansible.builtin.user:
    name: kali
    shell: /bin/bash

- name: Set XFCE Terminal background and foreground colors
  lineinfile:
    path: ~/.config/xfce4/terminal/terminalrc
    create: yes
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  loop:
    - { regexp: '^BackgroundColor=', line: 'BackgroundColor=#000000' }
    - { regexp: '^ForegroundColor=', line: 'ForegroundColor=#00FF00' }
    - { regexp: '^ColorPalette=', line: 'ColorPalette=#000000;#00FF00;#000000;#00FF00;#000000;#00FF00;#000000;#00FF00' }


