- name: Update wallpaper and lock screen image
  include_tasks: update_wallpaper.yml

- name: More minor config tasks
  include_tasks: config_tasks.yml

- name: Restart stuff
  include_tasks: restarts.yml

